services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /app/Persistence
    restart: "no"
    volumes:
      - ./:/app
    environment:
      ConnectionStrings__Default: ${CONNECTION_STRING}
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
    entrypoint: >
      /bin/bash -c "
        dotnet tool install --global dotnet-ef --version 9.0.2 &&
        export PATH=\"$PATH:/root/.dotnet/tools\" &&
        dotnet ef database update
      "
    depends_on:
      - db

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ConnectionStrings__Default: ${CONNECTION_STRING}
      TokensOptions__Secret: ${TOKENS_SECRET}
    ports:
      - "5000:8080"
    depends_on:
      - db
      - migrate
    volumes:
      - logs-volume:/app/logs

volumes:
  pgdata:
  logs-volume: