version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
      ConnectionStrings__Default: ${CONNECTION_STRING}
      TokensOptions__Secret: ${TOKENS_SECRET}
    ports:
      - "5000:8080"
    depends_on:
      - db
    volumes:
      - logs-volume:/app/logs

volumes:
  pgdata:
  logs-volume: